version: "3.9"

services:
  db:
    image: postgres:15
    container_name: asilo_db
    restart: always
    environment:
      POSTGRES_USER: dba_AsiloSystem 
      POSTGRES_PASSWORD: AsiloSystem!@
      POSTGRES_DB: asilo_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: asilo_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=asilo_db
      - DB_USER=dba_AsiloSystem
      - DB_PASSWORD=AsiloSystem!@
      - DB_HOST=db
      - DB_PORT=5432

  frontend:
    build: ./frontend
    container_name: asilo_frontend
    command: npm run dev -- --host 0.0.0.0
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data:

